# Generated by Django 3.1.3 on 2020-12-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodeldb',
            name='article_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='articlemodeldb',
            name='create_time',
            field=models.DateTimeField(default='1999-05-08 0:00'),
        ),
        migrations.AddField(
            model_name='articlemodeldb',
            name='image_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='articlemodeldb',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
