# Generated by Django 3.1.3 on 2020-12-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSite', '0002_auto_20201207_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodeldb',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
